#!/bin/bash
### this is done this way so it works with both v1 and v2
id3v2 -l "$@" \
  | egrep '^id3v2 tag info for |^Comment:|^/' \
  | sed 's/^.* Track: //g' \
  | sed 's|id3v2 tag info for \(.*\):$|\1|g' \
  | sed 's/: No ID3v2 tag$//g' \
  | paste - - \
  | sort -t$'\t' -n -k1 \
  | cut -f2
