#!/bin/bash
pid="$(cat "${PREFIX}/var/run/music-player.pid")"
state="$(ps -o state= -p "$pid")"
if [ "$state" ];then
  if [ "$state" = "T" ];then #it is stopped. let's send it a CONT
    exec music-unpause
  fi
  if [ "$state" = "S" ];then #it is running, let's pause it.
    exec music-pause
  fi
else
  nohup music-init &
  disown
fi
