#!/bin/sh
mkdir -p "${PREFIX}/run/music"
music_init_pid="${PREFIX}/run/music/init.pid"
if [ -f "${music_init_pid}" ];then
  if [ "$(ps -h -o cmd -p "$(cat "${music_init_pid}")")" = "qargs music-player" ];then
    printf "already running.\n"
    echo pid: "$(cat "${PREFIX}/run/music/init.pid")"
    echo cmd: "$(ps -h -o cmd -p $(cat ${PREFIX}/run/music/init.pid))"
    exit 1
  else
    logger -p notice -n logserver 'stale music init pid most likely.'
  fi
fi
export "QARGS_CHILD_PIDFILE=${PREFIX}/run/music/player.pid"
qargs music-player > $music_init_pid
rm ${PREFIX}/var/cache/music/nowplaying.txt
logger -p notice -n logserver 'ran out of music to play'
