#!/bin/bash
file="$(cat <(find -H /home/epoch/Music/ -type d) <(find -H /home/epoch/Music | egrep -i '\.m4a$|\.mp3$|\.flac$') | cut -d/ -f5- | dmenu -p music\> )"
if [ "$file" ];then
  music-stop
  music-playdir "/home/epoch/Music/$file"
  music-init
fi
