#!/bin/sh
logger -n logserver "attempting to stop the music."
rm -f ${PREFIX}/var/cache/music/nowplaying.txt
file="${PREFIX}/run/music/init.pid"
if [ -f "$file" ];then
  pid="$(cat "$file")"
  rm -f "$file"
  if [ "$(ps -h -o cmd -p "$pid")" = "qargs music-player" ];then
    printf "found qargs music-player running with pid %d. killing.\n" "$pid" >&2
    pkill -2 -P "$pid"
    kill -2 "$pid"
  else
    printf "stale init.pid\n" >&2
  fi
  file="${PREFIX}/run/music/player.pid"
  if [ -f "$file" ];then
    pid="$(cat "$file")"
    rm -f "$file"
    pkill -2 -P "$pid"
    kill -2 "$pid"
    exit 0
  fi
  logger -n logserver "player.pid was missing."
fi
logger -n logserver "init.pid was missing."
