#!/bin/bash
set -o pipefail
lsmod | grep snd_aloop > /dev/null || sudo modprobe snd_aloop
logger -p info -n logserver "RADIO IS NOW ON. http://$(domainname):8901/"
exec ncat -vklp 8901 -c music-stream
