#!/bin/sh
if [ -f "${PREFIX}/run/music/init.pid" ];then
  logger -p info -n logserver "music next'd"
  exec kill -USR2 "$(cat ${PREFIX}/run/music/init.pid)"
fi
logger -p info -n logserver "FAILED TO NEXT. PID FILE MISSING."
