#!/bin/bash
set -eo pipefail
logger -p info -n logserver "new listener! ${NCAT_REMOTE_ADDR}:${NCAT_REMOTE_PORT}"
icy_metaint=16384
while read -t 2 LINE;do
#  printf "%s\n" "$LINE"
  if printf "%s\n" "$LINE" | grep -i "^Icy-Metadata: " | cut -d: -f2- | grep 1 >/dev/null;then
    export want_icy=1
  fi
  if printf "%s\n" "$LINE" | grep -i "^Sixel-Albumart: " | cut -d: -f2- | grep 1 >/dev/null;then
    export want_six=1
  fi
  if [ "$LINE" = $'\r' ];then
    break
  fi
done

if [ "$want_icy" = "1" ];then
  printf "HTTP/1.1 200 OK\r\n"
  printf "icy-metaint: %s\r\n" "${icy_metaint}"
  printf "Content-Type: audio/ogg\r\n\r\n"
  music-record \
    | stdbuf -o0 oggenc - -r -C 2 -R 44100 -q 2 \
    | stdbuf -o0 icy-metadata "${icy_metaint}"
else
  printf "HTTP/1.1 200 OK\r\n"
  printf "Content-Type: audio/ogg\r\n\r\n"
  music-record \
    | stdbuf -o0 oggenc - -r -C 2 -R 44100 -q 2
fi
logger -p info -n logserver "a listener dropped out. :( ${NCAT_REMOTE_ADDR}:${NCAT_REMOTE_PORT}"
