#!/bin/bash
icy_metaint=1024
while read -t 2 LINE;do
  printf "%s\n" "$LINE" >&2
  printf "%s\n" "$LINE"
done \
  | if grep -i "Icy-Metadata:" | cut -d: -f2- | grep 1 >/dev/null;then
  printf "HTTP/1.1 200 OK\r\n"
  printf "icy-metaint: %s\r\n" "${icy_metaint}"
  printf "Content-Type: audio/mpeg\r\n\r\n"
  music-record \
    | stdbuf -o0 lame - -r \
    | icy-metadata "${icy_metaint}"
else
  printf "HTTP/1.1 200 OK\r\n"
  printf "Content-Type: audio/mpeg\r\n\r\n"
  music-record \
    | stdbuf -o0 lame - -r
fi
