#!/bin/bash
set -o pipefail
if printf "%s\n" "$1" | urimatch -D youtube.com >/dev/null;then
  music-setnowplaying "$(urititle "$1")" & #toss this in background so it won't hold up the song playing.
  exec youtube "$1"
fi
music-setnowplaying "$(music-fileinfo "$1")"
exec mpv --no-video --no-terminal "$1"
