#!/bin/sh
logger -n logserver "attempting to stop the music."
rm -f ${PREFIX}/var/cache/music/nowplaying.txt
file="${PREFIX}/run/music/init.pid"
if [ -f "$file" ];then
  pid="$(cat "$file")"
  rm -f "$file"
  kill -9 "$pid"
  file="${PREFIX}/run/music/player.pid"
  if [ -f "$file" ];then
    pid="$(cat "$file")"
    rm -f "$file"
    kill -9 "$pid"
    exit 0
  fi
  logger -n logserver "player.pid was missing."
fi
logger -n logserver "init.pid was missing."
