#!/bin/sh
if [ -f "${PREFIX}/run/music/player.pid" ];then
  logger -p info -n logserver 'music paused'
  exec kill -STOP "$(cat "${PREFIX}/run/music/player.pid")"
fi
logger -p info -n logserver 'MUSIC FAILED TO PAUSE. PID FILE MISSING.'
