#!/bin/sh
if [ -f "${PREFIX}/run/music/init.pid" ];then
  logger -p info -n logserver "music prev'd"
  exec kill -USR1 "$(cat "${PREFIX}/run/music/init.pid")"
fi
logger -p info -n logserver "FAILED TO PREV. MISSING PID FILE.""
