#!/bin/sh
FILE="/dev/null"
if [ -f "${PREFIX}/run/music/player.pid" ];then
  PID="$(cat "${PREFIX}/run/music/player.pid")"
  if [ -d "/proc/${PID}" ];then
    cd "/proc/${PID}/cwd"
    FILE="$(normalpath "$(cat "/proc/${PID}/cmdline" | tr '\0' '\n' | tail -n1)")"
  fi
fi
printf "%s\n" "$FILE"
