#!/bin/bash
pid="$(cat "${PREFIX}/var/run/music-player.pid")"
state="$(ps -o state= -p "$pid")"
if [ "$state" ];then
  if [ "$state" = "T" ];then #it is stopped. let's send it a CONT
    echo 'pause'
  fi
  if [ "$state" = "S" ];then #it is running, let's pause it.
    echo 'play'
  fi
else
  echo 'stop'
fi
